---
- name: Create a directory for the config
  file: path=/data/config state=directory mode=777

- name: Copy config
  copy:
    src: nginx.conf
    dest: "{{ nginx_config_path }}"

- name: Replace the proxy address in the config
  replace:
    path: "{{ nginx_config_path }}"
    regexp: "PRIVATE_IP_STORE"
    replace: "{{ PRIVATE_IP_STORE }}"
- replace:
    path: "{{ nginx_config_path }}"
    regexp: "PRIVATE_IP_VIEWER"
    replace: "{{ PRIVATE_IP_VIEWER }}"
- replace:
    path: "{{ nginx_config_path }}"
    regexp: "PORT_STORE"
    replace: "{{ PORT_STORE }}"
- replace:
    path: "{{ nginx_config_path }}"
    regexp: "PORT_VIEWER"
    replace: "{{ PORT_VIEWER }}"


- name: Start the Nginx proxy
  docker_container:
    name: "nginx"
    image: "{{ NGINX_IMAGE_REGISTRY }}{{ NGINX_IMAGE_NAME }}:{{ NGINX_IMAGE_TAG }}"
    restart: yes
    restart_policy: always
    detach: true
    published_ports: 80:80
    volumes:
    - "{{ nginx_config_path + ':' + nginx_config_path_in_docker }}"

- name: Start s-provenance viewer docker container
  docker_container:
    name: "viewer"
    image: "{{ SPROV_VIEWER_IMAGE_REGISTRY }}{{ SPROV_VIEWER_IMAGE_NAME }}:{{ SPROV_VIEWER_IMAGE_TAG }}"
    restart: yes
    restart_policy: always
    detach: true
    published_ports: "{{ PORT_VIEWER ~ ':8080' }}"