---
  - name: create mountpoints
    file:
      path: "{{ item.mount_dir }}"
      state: directory
      mode: 0777
    with_items:
    - "{{ NFS_IMPORTS }}" # Set in inventory 

  - name: NFS import
    mount:
      path: "{{ item.mount_dir }}" 
      src: "{{ item.nfs_location }}" 
      opts: "{{ NFS_OPTS }}" # Set in Inventory
      fstype: nfs
      state: mounted
    with_items:
    - "{{ NFS_IMPORTS }}" # Set in inventory 