---
- name: MongoDB
  tags:
    - mongodb
  hosts:
    - mongodb
  remote_user: "{{ REMOTE_USER }}"
  become_method: sudo
  become: true
  roles:
    - { role: roles/nfs-mounts }
    - { role: roles/docker/install }
    - { role: roles/docker/image,
        IMAGE_REGISTRY: "{{ MONGO_IMAGE_REGISTRY }}",
        IMAGE_NAME: "{{ MONGO_IMAGE_NAME }}",
        IMAGE_TAG: "{{ MONGO_IMAGE_TAG }}"
      }
    - { role: roles/mongodb }



