---
- name: Install Docker packages
  yum: name={{ item }} state=latest
  with_items: "{{ docker_packages }}"

- name: Install Docker python (pip) packages
  pip: name={{ item }}
  with_items: "{{ docker_py_pip_packages }}"

# If pip is not available, use yum via conditional install. Something like:
#    - name: Install Docker python (yum) packages
#      yum: name={{ item }} state=latest
#      with_items: docker-python
#      when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: start Docker
  service: name=docker state=started enabled=yes
